version: '3.1'

services: 
  api:
    container_name: api    
    image: node:18    
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "yarn --prod && yarn debug"
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - 5050:5050
      - 9222:9222
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/clean-node-api
      - JWT_SECRET=57a7b454baf24e6d-8f2c433ec6265a30
    links:
      - mongo
    networks:
      - dev

