version: '3.1'

services:

  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    volumes:
      - ./docker-data/mongo:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js # Mount the initialization script
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: --auth # Enable authentication

  mongo-express:
    container_name: mongo-express  
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123@Mudar
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  api:
    container_name: api    
    image: node:18    
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "yarn --prod && yarn debug"
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - 5050:5050
      - 9222:9222
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/clean-node-api
    links:
      - mongo

